apiVersion: apps/v1
kind: Deployment
metadata:
  name: q6
  labels:
    app: myapp6
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp6
  template:
    metadata:
      labels:
        app: myapp6
    spec:
      containers:
        - name: q6demo
          image: amar1999/myapp:v1
