apiVersion: apps/v1
kind: Deployment
metadata:
  name: q2
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: q2demo
          image: amar1999/myapp:v1
